spring:
    config:
        import: security-variable.yml
    mvc:
        static-path-pattern: /static/**
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/sns
        username: root
        password: ${mysql.password}
    thymeleaf:
        cache: false
    application:
        name: sns

mybatis:
    mapper-locations: mappers/*Mapper.xml